data:
  name: pl
  path: ./
  split: ./prompt_split.pt
  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False

model:
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: advance
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 6
  time_emb_mode: sin
  center_pos_mode: protein
  time_dependent_loss: False
  node_indicator: True
  model_type: prompt
  num_blocks: 1
  num_layers: 6
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 15
  knn: 32 # !
  num_node_types: 8
  act_fn: mish
  norm: True
  cutoff_mode: knn  # [radius, none]
  ew_net_type: global  # [r, m, none]
  num_x2h: 1
  num_h2x: 1
  r_max: 7.
  x2h_out_fc: False
  sync_twoup: False

train:
  seed: 2021
  batch_size: 1
  num_workers: 0
  n_acc_batch: 20
  max_iters: 1 # 8000
  val_freq: 1 # 60
  pos_noise_std: 0.1
  max_grad_norm: 10.0
  bond_loss_weight: 1.0
  optimizer:
    type: adam
    lr: 1.e-4
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 3
    min_lr: 5.e-6
